import type { Metadata } from 'next'
import './globals.css'
import RulesNav from "./components/blocks/RulesNav"

export const metadata: Metadata = {
  title: "Fortune's Favor",
  description: 'Generated by create next app',
}

export type nav = {
  title: string,
  href?: string,
  subroutes?: [nav]
}

const navRoutes: nav[] = [
  {
    "title": "Rules",
    "subroutes": [{
      "title": "Building A Character",
      "href": "/player_rules/getting_started/building_a_character"
    }]
  },
  {
    "title": "Classes",
    "subroutes": [{
      "title": "Brawler",
      "href": "/classes/brawler"
    }]
  },
  {
    "title": "Lineages",
    "href": "/lineages"
  }
]

export default function RootLayout({ children }: {children: React.ReactNode}) {
    return(
      <div className='container mx-auto max-w-screen-xxl'>
        <div className="h-screen flex">
            <div className="w-60 bg-gradient-to-b from-indigo-950 to-blue-900 p-4">
                <RulesNav navMap={navRoutes} />
            </div>
            <div className="flex-1 flex overflow-hidden pl-10">
                <div className="flex-1 overflow-y-scroll">
                    {children}
                </div>
            </div>
        </div>
      </div>
    )
}