import type { Metadata } from 'next'
import './globals.css'
import RulesNav from "./components/blocks/RulesNav"

export const metadata: Metadata = {
  title: "Fortune's Favor",
  description: 'Generated by create next app',
}

export type nav = {
  title: string,
  href?: string,
  subroutes?: nav[]
}

const navRoutes: nav[] = [
  {
    "title": "Rules",
    "subroutes": [{
      "title": "Building A Character",
      "href": "/player_rules/getting_started/building_a_character"
    },
    {
      "title": "Character Components",
      "href": "/player_rules/getting_started/character_components"
    },
    {
      "title": "Character Resources",
      "href": "/player_rules/getting_started/character_resources"
    },
    {
      "title": "Tests",
      "href": "/player_rules/getting_started/tests"
    },
    {
      "title": "Combat",
      "href": "/player_rules/getting_started/combat"
    },
    {
      "title": "Dying & Last Stand",
      "href": "/player_rules/getting_started/dying"
    },
    {
      "title": "Healing",
      "href": "/player_rules/getting_started/healing"
    },
    {
      "title": "Movement",
      "href": "/player_rules/getting_started/movement"
    },
    {
      "title": "Lift, Drag, & Pack",
      "href": "/player_rules/getting_started/lift_drag_pack"
    },
    {
      "title": "Equipment",
      "href": "/player_rules/getting_started/equipment"
    },
    {
      "title": "Reference",
      "href": "/player_rules/getting_started/references"
    }]
  },
  {
    "title": "Classes",
    "subroutes": [{
      "title": "Brawler",
      "href": "/classes/brawler"
    },
    {
      "title": "Devoted",
      "href": "/classes/devoted"
    },
    {
      "title": "Elementalist",
      "href": "/classes/elementalist"
    },
    {
      "title": "Knight",
      "href": "/classes/knight"
    },
    {
      "title": "Ranger",
      "href": "/classes/ranger"
    }]
  },
  {
    "title": "Lineages",
    "href": "/lineages"
  },
  {
    "title": "Cultures",
    "href": "/cultures"
  },
  {
    "title": "Generic Features",
    "subroutes": [
      {
        "title": "Novice Features",
        "href": "/generic_features/novice_features"
      },
      {
        "title": "Veteran Features",
        "href": "/generic_features/veteran_features"
      }
    ]
  }
]

export default function RootLayout({ children }: {children: React.ReactNode}) {
    return(
      <div className='container mx-auto max-w-screen-xxl bg-gray-900'>
        <div className="h-screen flex">
            <div className="w-60 bg-slate-950 p-4">
                <RulesNav navMap={navRoutes} />
            </div>
            <div className="flex-1 flex overflow-hidden pl-10">
                <div className="flex-1 overflow-y-scroll">
                    {children}
                </div>
            </div>
        </div>
      </div>
    )
}